FROM node:alpine

COPY . /src
WORKDIR /src

RUN apk update && apk add bash
RUN apk add openjdk11
RUN npm i -g firebase-tools

ENV GOOGLE_APPLICATION_CREDENTIALS sacc.json
EXPOSE 9099 4000

ENTRYPOINT ["firebase", "emulators:start", "--project", "demo-test"]
